#!/bin/bash

EXECMODE=S
case "$1" in
    -p|--parallel) EXECMODE=P; shift;;
    --) shift;;
esac

CMD='cd "{}"; echo "## $PWD"; git '"$@"

if [[ "$EXECMODE" == P ]]
then
    find "$PWD" -type d -name '.git' \
        | xargs dirname \
        | xargs -I{} -P0 bash -c "($CMD) > >(read -r -d '' BUFF; echo -e \"\$BUFF\") 2>&1"
else
    find "$PWD" -type d -name '.git' \
        | xargs dirname \
        | xargs -I{} bash -c "$CMD"
fi
