#!/bin/bash

EXECMODE=S
case "$1" in
    -p|--parallel) EXECMODE=P; shift;;
    --) shift;;
esac

CMD='cd "{}"; echo "## $PWD" >&2; git '"$@"

if [[ "$EXECMODE" == P ]]
then
    BUFFOUT='read -r -d "" BUFF; echo -e "$BUFF"'
    find "$PWD" -type d -name '.git' \
        | xargs dirname \
        | xargs -I{} -P0 bash -c "($CMD) > >($BUFFOUT) 2> >($BUFFOUT >&2)"
else
    find "$PWD" -type d -name '.git' \
        | xargs dirname \
        | xargs -I{} bash -c "$CMD"
fi
